# Generated by Django 5.0.2 on 2024-06-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='copmlete',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
