# Generated by Django 5.0.2 on 2024-07-09 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_order_copmlete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='copmlete',
            new_name='complete',
        ),
    ]
